language: node_js
sudo: false
dist: trusty
node_js:
- '6'
before_script:
- npm install -g grunt-cli
after_script:
- kill `pgrep microflo-linux`
before_install:
- openssl aes-256-cbc -K $encrypted_b877c04c0554_key -iv $encrypted_b877c04c0554_iv
  -in cookie.json.enc -out cookie.json -d
